on:
  push:
    branches: [main, master]
  pull_request:
  release:
    types: [published]
  workflow_dispatch:

name: test.yaml

permissions: read-all

jobs:
  test-MetaboanalystR:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: test-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install curl and other dependencies
        run: |
          sudo apt-get update
          sudo apt install curl libcairo2-dev libglpk-dev libnetcdf-dev pandoc

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV

      - name: Preprare environment
        run: source("prepare-environment.R")
        shell: Rscript {0}

      - name: Build site
        run: source("run-test.R")
        shell: Rscript {0}

      - name: Deploy to GitHub pages 
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs